# Generated by Django 3.2.9 on 2021-12-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('timetables', '0002_alter_timetable_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classe'),
        ),
    ]
