# Generated by Django 3.2.9 on 2021-12-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classe',
        ),
    ]
