# Generated by Django 3.2.9 on 2022-01-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('profiles', '0012_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classe',
        ),
        migrations.AddField(
            model_name='profile',
            name='classe',
            field=models.ManyToManyField(blank=True, to='classes.Classe'),
        ),
    ]
