# Generated by Django 3.2.9 on 2022-01-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('profiles', '0013_auto_20220104_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classe',
        ),
        migrations.AddField(
            model_name='profile',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classe'),
        ),
    ]
