# Generated by Django 3.2.9 on 2021-11-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.FileField(null=True, upload_to='course_content/'),
        ),
    ]
