# Generated by Django 3.2.9 on 2021-12-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0005_alter_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classe'),
        ),
    ]
